services:
  agent-core:
    build:
      context: ./agent_core_py
    volumes:
      - $HOME/.podlet:/root/.podlet
    networks:
      - podlet-internal
    restart: unless-stopped

  gateway:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - PODLET_DOCKER=1
      - LLM_SERVICE_HOST=agent-core
    volumes:
      - $HOME/.podlet:/root/.podlet
    networks:
      - podlet-internal
    depends_on:
      - agent-core
    restart: on-failure
    tty: true
    stdin_open: true

networks:
  podlet-internal:
